services:
  embryotech-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: embryotech-app
    ports:
      - "5001:5001"
    environment:
      # Configurações do banco de dados
      - DB_USER=postgres
      - DB_PASSWORD=CHESS5558a72
      - DB_HOST=212.85.1.215
      - DB_PORT=5432
      - DB_NAME=embryotech

      # Chaves de segurança
      - SECRET_KEY=sua_chave_gerada_com_token_urlsafe_32_docker
      - JWT_SECRET_KEY=sua_chave_gerada_com_token_hex_32_docker

      # Configurações do Flask
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DEBUG=False
      - DOCKER_ENV=true

      # Configuração da porta
      - PORT=5001

    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
      - ./logs:/app/logs

    restart: unless-stopped
    networks:
      - minha_network

    # Health check para verificar se a aplicação está rodando
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  minha_network:
    external: true
