services:
  web:
    build:
      context: . # O contexto é a raiz do seu projeto (onde está seu_projeto/)
      dockerfile: Dockerfile # O Dockerfile está na raiz do seu_projeto/
    ports:
      - "9001:9001"

    environment:
      DEBUG: "True"
    env_file:
      - ./Backend/.env # Aponta para o .env dentro da pasta Backend
    volumes:
      # Monta a raiz do projeto no /app dentro do contêiner.
      # Seus arquivos Backend estarão em /app/Backend, Frontend em /app/Frontend.
      # Mas o WORKDIR do Dockerfile é /app/Backend
      - ./Backend:/app/Backend # Monta sua pasta Backend para /app/Backend no contêiner
      - ./Frontend:/app/Frontend # Monta sua pasta Frontend para /app/Frontend no contêiner
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh # Monta o script wait-for-it.sh
    restart: always
